# Generated by Django 2.2.16 on 2023-05-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230520_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
