# Generated by Django 2.2.16 on 2023-05-24 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRecipes',
            new_name='FavoriteRecipe',
        ),
    ]
