# Generated by Django 2.2.16 on 2023-05-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230521_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='count',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='count',
            new_name='amount',
        ),
    ]
