# Generated by Django 2.2.16 on 2023-05-20 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20230515_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedRecipes',
            new_name='FavoriteRecipes',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
